// ============================================================
// SERVICE CATEGORIES (20)
// ============================================================

export const SERVICE_CATEGORIES = [
  { slug: 'penetration-testing', name: 'Penetration Testing', icon: '🎯', description: 'Offensive security testing to identify vulnerabilities before attackers do. Includes network, web app, mobile, and social engineering assessments.' },
  { slug: 'managed-security', name: 'Managed Security Services (MSSP)', icon: '🛡️', description: '24/7 security monitoring, threat detection, and incident response from a dedicated security operations center.' },
  { slug: 'incident-response', name: 'Incident Response', icon: '🚨', description: 'Rapid breach investigation, containment, eradication, and recovery services when a security incident occurs.' },
  { slug: 'compliance-assessment', name: 'Compliance & Audit', icon: '📋', description: 'SOC 2, HIPAA, PCI-DSS, ISO 27001, and other compliance framework assessments and audit preparation.' },
  { slug: 'grc', name: 'Governance, Risk & Compliance', icon: '⚖️', description: 'Enterprise risk management frameworks, policy development, and regulatory compliance programs.' },
  { slug: 'vciso', name: 'Virtual CISO', icon: '👔', description: 'Fractional security leadership providing strategic guidance, program development, and board-level reporting.' },
  { slug: 'security-awareness', name: 'Security Awareness Training', icon: '🎓', description: 'Employee security training, phishing simulations, and security culture programs to reduce human risk.' },
  { slug: 'vulnerability-management', name: 'Vulnerability Management', icon: '🔍', description: 'Continuous vulnerability scanning, prioritization, and remediation tracking across your environment.' },
  { slug: 'cloud-security', name: 'Cloud Security', icon: '☁️', description: 'AWS, Azure, and GCP security architecture, configuration review, and cloud-native security solutions.' },
  { slug: 'identity-access', name: 'Identity & Access Management', icon: '🔑', description: 'SSO, MFA, directory services, privileged access management, and zero trust architecture.' },
  { slug: 'network-security', name: 'Network Security', icon: '🌐', description: 'Firewall management, network segmentation, intrusion detection, and network monitoring solutions.' },
  { slug: 'email-security', name: 'Email Security', icon: '📧', description: 'Anti-phishing, DMARC/DKIM/SPF configuration, email encryption, and business email compromise prevention.' },
  { slug: 'endpoint-security', name: 'Endpoint Security', icon: '💻', description: 'EDR, MDR, device management, and endpoint protection platforms for laptops, servers, and mobile devices.' },
  { slug: 'application-security', name: 'Application Security', icon: '🔐', description: 'Code review, SAST/DAST testing, DevSecOps integration, and secure development lifecycle consulting.' },
  { slug: 'data-protection', name: 'Data Protection', icon: '🗄️', description: 'Data loss prevention, encryption, backup solutions, and data classification programs.' },
  { slug: 'threat-intelligence', name: 'Threat Intelligence', icon: '🔭', description: 'Threat feeds, dark web monitoring, adversary tracking, and threat landscape analysis.' },
  { slug: 'security-consulting', name: 'Security Consulting', icon: '💡', description: 'Strategic security advisory, program assessments, roadmap development, and security architecture review.' },
  { slug: 'ot-ics-security', name: 'OT/ICS Security', icon: '🏭', description: 'Industrial control system and SCADA security for manufacturing, energy, and critical infrastructure.' },
  { slug: 'digital-forensics', name: 'Digital Forensics', icon: '🔬', description: 'Computer forensics, evidence collection, chain of custody, and expert witness services for legal proceedings.' },
  { slug: 'red-teaming', name: 'Red Teaming', icon: '🏴', description: 'Advanced adversary simulation combining multiple attack vectors to test organizational detection and response capabilities.' },
];

// ============================================================
// PROVIDERS (50 real cybersecurity companies)
// ============================================================

export const PROVIDERS = [
  {
    slug: 'crowdstrike',
    name: 'CrowdStrike',
    description: 'Leader in cloud-delivered endpoint and workload protection. Known for the Falcon platform combining EDR, threat intelligence, and managed hunting.',
    website: 'https://www.crowdstrike.com',
    founded_year: 2011,
    headquarters: 'Austin, TX',
    city: 'Austin',
    state: 'Texas',
    state_code: 'TX',
    employee_count: '5000+',
    industries_served: ['technology', 'finance', 'healthcare', 'government', 'retail'],
    services: ['endpoint-security', 'threat-intelligence', 'managed-security', 'incident-response'],
  },
  {
    slug: 'palo-alto-networks',
    name: 'Palo Alto Networks',
    description: 'Global cybersecurity leader offering next-generation firewalls, cloud security, and AI-driven security operations.',
    website: 'https://www.paloaltonetworks.com',
    founded_year: 2005,
    headquarters: 'Santa Clara, CA',
    city: 'Santa Clara',
    state: 'California',
    state_code: 'CA',
    employee_count: '10000+',
    industries_served: ['technology', 'finance', 'government', 'healthcare'],
    services: ['network-security', 'cloud-security', 'endpoint-security', 'managed-security'],
  },
  {
    slug: 'rapid7',
    name: 'Rapid7',
    description: 'Provides security analytics and automation solutions including InsightVM for vulnerability management and InsightIDR for detection and response.',
    website: 'https://www.rapid7.com',
    founded_year: 2000,
    headquarters: 'Boston, MA',
    city: 'Boston',
    state: 'Massachusetts',
    state_code: 'MA',
    employee_count: '2000-5000',
    industries_served: ['technology', 'finance', 'healthcare', 'retail'],
    services: ['vulnerability-management', 'managed-security', 'penetration-testing', 'cloud-security'],
  },
  {
    slug: 'secureworks',
    name: 'Secureworks',
    description: 'Dell Technologies subsidiary delivering managed security services, threat intelligence, and security consulting to organizations worldwide.',
    website: 'https://www.secureworks.com',
    founded_year: 1999,
    headquarters: 'Atlanta, GA',
    city: 'Atlanta',
    state: 'Georgia',
    state_code: 'GA',
    employee_count: '2000-5000',
    industries_served: ['finance', 'healthcare', 'manufacturing', 'retail'],
    services: ['managed-security', 'threat-intelligence', 'vulnerability-management', 'incident-response'],
  },
  {
    slug: 'optiv',
    name: 'Optiv Security',
    description: 'One of the largest pure-play cybersecurity solutions integrators, offering end-to-end cyber advisory and managed services.',
    website: 'https://www.optiv.com',
    founded_year: 2015,
    headquarters: 'Denver, CO',
    city: 'Denver',
    state: 'Colorado',
    state_code: 'CO',
    employee_count: '2000-5000',
    industries_served: ['finance', 'healthcare', 'energy', 'retail', 'technology'],
    services: ['security-consulting', 'identity-access', 'cloud-security', 'grc'],
  },
  {
    slug: 'coalfire',
    name: 'Coalfire',
    description: 'Leading cybersecurity advisory firm specializing in compliance, risk management, and technical testing for cloud-forward organizations.',
    website: 'https://www.coalfire.com',
    founded_year: 2001,
    headquarters: 'Denver, CO',
    city: 'Denver',
    state: 'Colorado',
    state_code: 'CO',
    employee_count: '500-1000',
    industries_served: ['technology', 'finance', 'healthcare', 'government'],
    services: ['compliance-assessment', 'penetration-testing', 'cloud-security', 'grc'],
  },
  {
    slug: 'bishop-fox',
    name: 'Bishop Fox',
    description: 'Offensive security firm known for expert penetration testing, red teaming, and application security assessments.',
    website: 'https://www.bishopfox.com',
    founded_year: 2005,
    headquarters: 'Phoenix, AZ',
    city: 'Phoenix',
    state: 'Arizona',
    state_code: 'AZ',
    employee_count: '200-500',
    industries_served: ['technology', 'finance', 'healthcare'],
    services: ['penetration-testing', 'red-teaming', 'application-security'],
  },
  {
    slug: 'ncc-group',
    name: 'NCC Group',
    description: 'Global cyber and software resilience company providing assurance, consulting, and managed services.',
    website: 'https://www.nccgroup.com',
    founded_year: 1999,
    headquarters: 'New York, NY',
    city: 'New York',
    state: 'New York',
    state_code: 'NY',
    employee_count: '2000-5000',
    industries_served: ['finance', 'technology', 'government', 'energy'],
    services: ['penetration-testing', 'security-consulting', 'incident-response', 'application-security'],
  },
  {
    slug: 'trustwave',
    name: 'Trustwave',
    description: 'Singtel subsidiary offering managed security services, consulting, and threat intelligence focused on mid-market organizations.',
    website: 'https://www.trustwave.com',
    founded_year: 1995,
    headquarters: 'Chicago, IL',
    city: 'Chicago',
    state: 'Illinois',
    state_code: 'IL',
    employee_count: '1000-2000',
    industries_served: ['retail', 'finance', 'healthcare', 'hospitality'],
    services: ['managed-security', 'compliance-assessment', 'penetration-testing', 'digital-forensics'],
  },
  {
    slug: 'arctic-wolf',
    name: 'Arctic Wolf',
    description: 'Security operations company providing cloud-native managed detection and response (MDR) and security awareness training.',
    website: 'https://arcticwolf.com',
    founded_year: 2012,
    headquarters: 'Minneapolis, MN',
    city: 'Minneapolis',
    state: 'Minnesota',
    state_code: 'MN',
    employee_count: '1000-2000',
    industries_served: ['finance', 'healthcare', 'manufacturing', 'legal'],
    services: ['managed-security', 'vulnerability-management', 'security-awareness', 'incident-response'],
  },
  {
    slug: 'guidepoint-security',
    name: 'GuidePoint Security',
    description: 'Cybersecurity consulting firm helping organizations make better decisions and minimize risk through expert advisory and solutions.',
    website: 'https://www.guidepointsecurity.com',
    founded_year: 2011,
    headquarters: 'Herndon, VA',
    city: 'Herndon',
    state: 'Virginia',
    state_code: 'VA',
    employee_count: '500-1000',
    industries_served: ['government', 'finance', 'healthcare', 'technology'],
    services: ['security-consulting', 'cloud-security', 'identity-access', 'grc'],
  },
  {
    slug: 'proofpoint',
    name: 'Proofpoint',
    description: 'Leading cybersecurity and compliance company protecting organizations against advanced threats and compliance risks through email and cloud security.',
    website: 'https://www.proofpoint.com',
    founded_year: 2002,
    headquarters: 'Sunnyvale, CA',
    city: 'Sunnyvale',
    state: 'California',
    state_code: 'CA',
    employee_count: '5000+',
    industries_served: ['finance', 'healthcare', 'technology', 'government'],
    services: ['email-security', 'security-awareness', 'data-protection', 'compliance-assessment'],
  },
  {
    slug: 'sentinel-one',
    name: 'SentinelOne',
    description: 'AI-powered cybersecurity platform providing autonomous endpoint protection, detection, and response across the enterprise.',
    website: 'https://www.sentinelone.com',
    founded_year: 2013,
    headquarters: 'Mountain View, CA',
    city: 'Mountain View',
    state: 'California',
    state_code: 'CA',
    employee_count: '2000-5000',
    industries_served: ['technology', 'finance', 'healthcare', 'energy'],
    services: ['endpoint-security', 'managed-security', 'threat-intelligence', 'cloud-security'],
  },
  {
    slug: 'tenable',
    name: 'Tenable',
    description: 'Cyber exposure management company helping organizations understand and reduce cybersecurity risk across their attack surface.',
    website: 'https://www.tenable.com',
    founded_year: 2002,
    headquarters: 'Columbia, MD',
    city: 'Columbia',
    state: 'Maryland',
    state_code: 'MD',
    employee_count: '1000-2000',
    industries_served: ['technology', 'finance', 'government', 'healthcare'],
    services: ['vulnerability-management', 'cloud-security', 'ot-ics-security', 'compliance-assessment'],
  },
  {
    slug: 'mandiant',
    name: 'Mandiant (Google Cloud)',
    description: 'World-renowned incident response and threat intelligence firm, now part of Google Cloud, known for tracking advanced persistent threats.',
    website: 'https://www.mandiant.com',
    founded_year: 2004,
    headquarters: 'Reston, VA',
    city: 'Reston',
    state: 'Virginia',
    state_code: 'VA',
    employee_count: '2000-5000',
    industries_served: ['government', 'finance', 'technology', 'energy'],
    services: ['incident-response', 'threat-intelligence', 'red-teaming', 'security-consulting'],
  },
  {
    slug: 'kroll',
    name: 'Kroll',
    description: 'Global risk and financial advisory firm with deep expertise in cyber risk, digital forensics, and incident response.',
    website: 'https://www.kroll.com',
    founded_year: 1972,
    headquarters: 'New York, NY',
    city: 'New York',
    state: 'New York',
    state_code: 'NY',
    employee_count: '5000+',
    industries_served: ['finance', 'legal', 'healthcare', 'technology'],
    services: ['digital-forensics', 'incident-response', 'threat-intelligence', 'grc'],
  },
  {
    slug: 'deepwatch',
    name: 'Deepwatch',
    description: 'Advanced managed detection and response (MDR) platform delivering 24/7 security monitoring tailored to mid-market enterprises.',
    website: 'https://www.deepwatch.com',
    founded_year: 2019,
    headquarters: 'Denver, CO',
    city: 'Denver',
    state: 'Colorado',
    state_code: 'CO',
    employee_count: '200-500',
    industries_served: ['finance', 'healthcare', 'technology', 'retail'],
    services: ['managed-security', 'vulnerability-management', 'endpoint-security'],
  },
  {
    slug: 'netskope',
    name: 'Netskope',
    description: 'Cloud security leader providing SASE, CASB, and zero trust network access to protect data and users everywhere.',
    website: 'https://www.netskope.com',
    founded_year: 2012,
    headquarters: 'Santa Clara, CA',
    city: 'Santa Clara',
    state: 'California',
    state_code: 'CA',
    employee_count: '2000-5000',
    industries_served: ['technology', 'finance', 'healthcare', 'manufacturing'],
    services: ['cloud-security', 'data-protection', 'network-security', 'identity-access'],
  },
  {
    slug: 'reliaquest',
    name: 'ReliaQuest',
    description: 'Security operations platform company providing GreyMatter for unified visibility, detection, and response across security tools.',
    website: 'https://www.reliaquest.com',
    founded_year: 2007,
    headquarters: 'Tampa, FL',
    city: 'Tampa',
    state: 'Florida',
    state_code: 'FL',
    employee_count: '1000-2000',
    industries_served: ['finance', 'healthcare', 'retail', 'technology'],
    services: ['managed-security', 'threat-intelligence', 'endpoint-security', 'cloud-security'],
  },
  {
    slug: 'critical-start',
    name: 'Critical Start',
    description: 'Managed detection and response provider with a unique Trusted Behavior Registry that reduces alert noise for security teams.',
    website: 'https://www.criticalstart.com',
    founded_year: 2012,
    headquarters: 'Plano, TX',
    city: 'Plano',
    state: 'Texas',
    state_code: 'TX',
    employee_count: '200-500',
    industries_served: ['finance', 'healthcare', 'legal', 'manufacturing'],
    services: ['managed-security', 'endpoint-security', 'vulnerability-management', 'security-consulting'],
  },
  {
    slug: 'a-lign',
    name: 'A-LIGN',
    description: 'Technology-enabled compliance and cybersecurity firm specializing in SOC 2, ISO 27001, PCI-DSS, and HITRUST assessments.',
    website: 'https://www.a-lign.com',
    founded_year: 2009,
    headquarters: 'Tampa, FL',
    city: 'Tampa',
    state: 'Florida',
    state_code: 'FL',
    employee_count: '500-1000',
    industries_served: ['technology', 'finance', 'healthcare'],
    services: ['compliance-assessment', 'penetration-testing', 'grc'],
  },
  {
    slug: 'schellman',
    name: 'Schellman',
    description: 'Global independent security and privacy compliance assessor specializing in SOC, ISO, PCI, and FedRAMP audits.',
    website: 'https://www.schellman.com',
    founded_year: 2003,
    headquarters: 'Tampa, FL',
    city: 'Tampa',
    state: 'Florida',
    state_code: 'FL',
    employee_count: '200-500',
    industries_served: ['technology', 'finance', 'government', 'healthcare'],
    services: ['compliance-assessment', 'penetration-testing', 'grc'],
  },
  {
    slug: 'dragos',
    name: 'Dragos',
    description: 'Industrial cybersecurity company specializing in OT/ICS threat detection and response for critical infrastructure.',
    website: 'https://www.dragos.com',
    founded_year: 2016,
    headquarters: 'Hanover, MD',
    city: 'Hanover',
    state: 'Maryland',
    state_code: 'MD',
    employee_count: '500-1000',
    industries_served: ['energy', 'manufacturing', 'government', 'utilities'],
    services: ['ot-ics-security', 'threat-intelligence', 'incident-response', 'vulnerability-management'],
  },
  {
    slug: 'claroty',
    name: 'Claroty',
    description: 'Industrial and healthcare cybersecurity platform providing visibility and protection for OT, IoT, and IoMT environments.',
    website: 'https://www.claroty.com',
    founded_year: 2015,
    headquarters: 'New York, NY',
    city: 'New York',
    state: 'New York',
    state_code: 'NY',
    employee_count: '500-1000',
    industries_served: ['healthcare', 'manufacturing', 'energy', 'government'],
    services: ['ot-ics-security', 'vulnerability-management', 'network-security'],
  },
  {
    slug: 'synack',
    name: 'Synack',
    description: 'Crowdsourced security testing platform combining a global network of ethical hackers with AI to deliver comprehensive pentesting.',
    website: 'https://www.synack.com',
    founded_year: 2013,
    headquarters: 'Redwood City, CA',
    city: 'Redwood City',
    state: 'California',
    state_code: 'CA',
    employee_count: '200-500',
    industries_served: ['technology', 'finance', 'government', 'healthcare'],
    services: ['penetration-testing', 'vulnerability-management', 'application-security', 'red-teaming'],
  },
  {
    slug: 'netspi',
    name: 'NetSPI',
    description: 'Proactive security solutions provider specializing in penetration testing, attack surface management, and breach simulation.',
    website: 'https://www.netspi.com',
    founded_year: 2001,
    headquarters: 'Minneapolis, MN',
    city: 'Minneapolis',
    state: 'Minnesota',
    state_code: 'MN',
    employee_count: '500-1000',
    industries_served: ['finance', 'healthcare', 'technology', 'retail'],
    services: ['penetration-testing', 'red-teaming', 'vulnerability-management', 'application-security'],
  },
  {
    slug: 'bugcrowd',
    name: 'Bugcrowd',
    description: 'Crowdsourced cybersecurity platform offering bug bounty programs, penetration testing, and vulnerability disclosure management.',
    website: 'https://www.bugcrowd.com',
    founded_year: 2012,
    headquarters: 'San Francisco, CA',
    city: 'San Francisco',
    state: 'California',
    state_code: 'CA',
    employee_count: '200-500',
    industries_served: ['technology', 'finance', 'government', 'healthcare'],
    services: ['penetration-testing', 'vulnerability-management', 'application-security'],
  },
  {
    slug: 'expel',
    name: 'Expel',
    description: 'Transparent managed detection and response provider known for clear metrics, no lock-in, and a modern SOC-as-a-service approach.',
    website: 'https://www.expel.com',
    founded_year: 2016,
    headquarters: 'Herndon, VA',
    city: 'Herndon',
    state: 'Virginia',
    state_code: 'VA',
    employee_count: '500-1000',
    industries_served: ['technology', 'finance', 'healthcare', 'retail'],
    services: ['managed-security', 'cloud-security', 'endpoint-security', 'vulnerability-management'],
  },
  {
    slug: 'lmg-security',
    name: 'LMG Security',
    description: 'Cybersecurity consulting firm offering incident response, penetration testing, and training with a focus on practical, real-world security.',
    website: 'https://www.lmgsecurity.com',
    founded_year: 2007,
    headquarters: 'Missoula, MT',
    city: 'Missoula',
    state: 'Montana',
    state_code: 'MT',
    employee_count: '50-200',
    industries_served: ['healthcare', 'finance', 'education', 'government'],
    services: ['incident-response', 'penetration-testing', 'security-awareness', 'digital-forensics'],
  },
  {
    slug: 'binary-defense',
    name: 'Binary Defense',
    description: 'Managed security services provider combining human intelligence with technology for threat detection, hunting, and response.',
    website: 'https://www.binarydefense.com',
    founded_year: 2014,
    headquarters: 'Stow, OH',
    city: 'Stow',
    state: 'Ohio',
    state_code: 'OH',
    employee_count: '200-500',
    industries_served: ['finance', 'healthcare', 'manufacturing', 'retail'],
    services: ['managed-security', 'threat-intelligence', 'endpoint-security', 'incident-response'],
  },
  {
    slug: 'nvisium',
    name: 'nVisium',
    description: 'Application security consulting firm specializing in secure code review, dynamic testing, and DevSecOps transformation.',
    website: 'https://www.nvisium.com',
    founded_year: 2009,
    headquarters: 'Falls Church, VA',
    city: 'Falls Church',
    state: 'Virginia',
    state_code: 'VA',
    employee_count: '50-200',
    industries_served: ['technology', 'finance', 'healthcare'],
    services: ['application-security', 'penetration-testing', 'security-consulting', 'cloud-security'],
  },
  {
    slug: 'cyderes',
    name: 'Cyderes',
    description: 'Modern managed security company providing 24/7 SOC services, threat hunting, and security engineering for growing enterprises.',
    website: 'https://www.cyderes.com',
    founded_year: 2019,
    headquarters: 'Kansas City, MO',
    city: 'Kansas City',
    state: 'Missouri',
    state_code: 'MO',
    employee_count: '200-500',
    industries_served: ['finance', 'healthcare', 'technology', 'manufacturing'],
    services: ['managed-security', 'identity-access', 'cloud-security', 'security-consulting'],
  },
  {
    slug: 'blumira',
    name: 'Blumira',
    description: 'Automated SIEM and XDR platform designed for mid-market organizations, providing detection and response without the complexity.',
    website: 'https://www.blumira.com',
    founded_year: 2018,
    headquarters: 'Ann Arbor, MI',
    city: 'Ann Arbor',
    state: 'Michigan',
    state_code: 'MI',
    employee_count: '50-200',
    industries_served: ['healthcare', 'finance', 'manufacturing', 'education'],
    services: ['managed-security', 'cloud-security', 'network-security'],
  },
  {
    slug: 'horizon3ai',
    name: 'Horizon3.ai',
    description: 'Autonomous penetration testing platform (NodeZero) enabling organizations to continuously find and fix exploitable attack paths.',
    website: 'https://www.horizon3.ai',
    founded_year: 2019,
    headquarters: 'San Francisco, CA',
    city: 'San Francisco',
    state: 'California',
    state_code: 'CA',
    employee_count: '50-200',
    industries_served: ['technology', 'finance', 'government', 'healthcare'],
    services: ['penetration-testing', 'vulnerability-management', 'red-teaming'],
  },
  {
    slug: 'knowbe4',
    name: 'KnowBe4',
    description: 'World\'s largest security awareness training and simulated phishing platform, helping organizations manage the ongoing problem of social engineering.',
    website: 'https://www.knowbe4.com',
    founded_year: 2010,
    headquarters: 'Clearwater, FL',
    city: 'Clearwater',
    state: 'Florida',
    state_code: 'FL',
    employee_count: '1000-2000',
    industries_served: ['finance', 'healthcare', 'technology', 'government', 'education'],
    services: ['security-awareness', 'compliance-assessment', 'email-security'],
  },
  {
    slug: 'corvus-insurance',
    name: 'Corvus Insurance',
    description: 'Cyber insurance provider that uses AI-driven risk assessment to help organizations understand and reduce their cyber exposure.',
    website: 'https://www.corvusinsurance.com',
    founded_year: 2017,
    headquarters: 'Boston, MA',
    city: 'Boston',
    state: 'Massachusetts',
    state_code: 'MA',
    employee_count: '200-500',
    industries_served: ['finance', 'healthcare', 'technology', 'retail'],
    services: ['grc', 'vulnerability-management', 'security-consulting'],
  },
  {
    slug: 'cybereason',
    name: 'Cybereason',
    description: 'AI-powered endpoint detection and response platform delivering military-grade protection against advanced cyber attacks.',
    website: 'https://www.cybereason.com',
    founded_year: 2012,
    headquarters: 'Boston, MA',
    city: 'Boston',
    state: 'Massachusetts',
    state_code: 'MA',
    employee_count: '500-1000',
    industries_served: ['finance', 'technology', 'government', 'healthcare'],
    services: ['endpoint-security', 'managed-security', 'incident-response', 'threat-intelligence'],
  },
  {
    slug: 'trellix',
    name: 'Trellix',
    description: 'XDR company formed from the merger of McAfee Enterprise and FireEye, providing living security that learns and adapts to protect operations.',
    website: 'https://www.trellix.com',
    founded_year: 2022,
    headquarters: 'Milpitas, CA',
    city: 'Milpitas',
    state: 'California',
    state_code: 'CA',
    employee_count: '5000+',
    industries_served: ['government', 'finance', 'healthcare', 'energy'],
    services: ['endpoint-security', 'email-security', 'network-security', 'data-protection'],
  },
  {
    slug: 'sophos',
    name: 'Sophos',
    description: 'Global leader in next-generation cybersecurity, protecting businesses with AI-powered endpoint, network, email, and cloud security solutions.',
    website: 'https://www.sophos.com',
    founded_year: 1985,
    headquarters: 'Burlington, MA',
    city: 'Burlington',
    state: 'Massachusetts',
    state_code: 'MA',
    employee_count: '5000+',
    industries_served: ['healthcare', 'education', 'retail', 'government', 'manufacturing'],
    services: ['endpoint-security', 'network-security', 'managed-security', 'email-security'],
  },
  {
    slug: 'cynet',
    name: 'Cynet',
    description: 'Autonomous breach protection platform combining XDR with automated response and 24/7 MDR for mid-market organizations.',
    website: 'https://www.cynet.com',
    founded_year: 2015,
    headquarters: 'New York, NY',
    city: 'New York',
    state: 'New York',
    state_code: 'NY',
    employee_count: '200-500',
    industries_served: ['finance', 'healthcare', 'technology', 'legal'],
    services: ['endpoint-security', 'managed-security', 'vulnerability-management', 'incident-response'],
  },
  {
    slug: 'at-bay',
    name: 'At-Bay',
    description: 'InsurSec company combining insurance with proactive security monitoring to help organizations reduce cyber risk and secure better coverage.',
    website: 'https://www.at-bay.com',
    founded_year: 2016,
    headquarters: 'San Francisco, CA',
    city: 'San Francisco',
    state: 'California',
    state_code: 'CA',
    employee_count: '200-500',
    industries_served: ['technology', 'finance', 'retail', 'professional-services'],
    services: ['grc', 'vulnerability-management', 'security-consulting'],
  },
  {
    slug: 'socradar',
    name: 'SOCRadar',
    description: 'Extended threat intelligence platform providing attack surface management, digital risk protection, and dark web monitoring.',
    website: 'https://www.socradar.io',
    founded_year: 2018,
    headquarters: 'Wilmington, DE',
    city: 'Wilmington',
    state: 'Delaware',
    state_code: 'DE',
    employee_count: '200-500',
    industries_served: ['finance', 'technology', 'government', 'healthcare'],
    services: ['threat-intelligence', 'vulnerability-management', 'digital-forensics'],
  },
  {
    slug: 'securonix',
    name: 'Securonix',
    description: 'Cloud-native SIEM and UEBA platform using machine learning to detect insider threats and advanced attacks across the enterprise.',
    website: 'https://www.securonix.com',
    founded_year: 2008,
    headquarters: 'Addison, TX',
    city: 'Addison',
    state: 'Texas',
    state_code: 'TX',
    employee_count: '1000-2000',
    industries_served: ['finance', 'healthcare', 'energy', 'government'],
    services: ['managed-security', 'threat-intelligence', 'cloud-security', 'identity-access'],
  },
  {
    slug: 'huntress',
    name: 'Huntress',
    description: 'Managed security platform built for SMBs and the MSPs that support them, providing EDR, ITDR, and a 24/7 human-powered SOC.',
    website: 'https://www.huntress.com',
    founded_year: 2015,
    headquarters: 'Baltimore, MD',
    city: 'Baltimore',
    state: 'Maryland',
    state_code: 'MD',
    employee_count: '500-1000',
    industries_served: ['technology', 'healthcare', 'finance', 'education'],
    services: ['managed-security', 'endpoint-security', 'identity-access', 'security-awareness'],
  },
  {
    slug: 'cyber-defense-labs',
    name: 'Cyber Defense Labs',
    description: 'Boutique cybersecurity firm providing penetration testing, vulnerability assessments, and security program development.',
    website: 'https://www.cyberdefenselabs.com',
    founded_year: 2016,
    headquarters: 'Tulsa, OK',
    city: 'Tulsa',
    state: 'Oklahoma',
    state_code: 'OK',
    employee_count: '50-200',
    industries_served: ['energy', 'finance', 'healthcare', 'technology'],
    services: ['penetration-testing', 'vulnerability-management', 'vciso', 'security-consulting'],
  },
  {
    slug: 'cipher',
    name: 'Cipher (Prosegur)',
    description: 'Global managed security services provider offering SOC-as-a-service, threat intelligence, and cyber risk management.',
    website: 'https://www.cipher.com',
    founded_year: 2000,
    headquarters: 'Miami, FL',
    city: 'Miami',
    state: 'Florida',
    state_code: 'FL',
    employee_count: '500-1000',
    industries_served: ['finance', 'healthcare', 'retail', 'energy'],
    services: ['managed-security', 'threat-intelligence', 'grc', 'vulnerability-management'],
  },
  {
    slug: 'trimarc-security',
    name: 'Trimarc Security',
    description: 'Active Directory and identity security experts providing assessments, hardening, and monitoring for enterprise environments.',
    website: 'https://www.trimarcsecurity.com',
    founded_year: 2015,
    headquarters: 'Seattle, WA',
    city: 'Seattle',
    state: 'Washington',
    state_code: 'WA',
    employee_count: '10-50',
    industries_served: ['finance', 'government', 'healthcare', 'technology'],
    services: ['identity-access', 'security-consulting', 'penetration-testing'],
  },
  {
    slug: 'sevn-x',
    name: 'SevnX',
    description: 'vCISO and security advisory firm helping mid-market companies build and mature their cybersecurity programs.',
    website: 'https://www.sevnx.com',
    founded_year: 2020,
    headquarters: 'Charlotte, NC',
    city: 'Charlotte',
    state: 'North Carolina',
    state_code: 'NC',
    employee_count: '10-50',
    industries_served: ['finance', 'healthcare', 'technology', 'manufacturing'],
    services: ['vciso', 'grc', 'security-consulting', 'compliance-assessment'],
  },
  {
    slug: 'cybermaxx',
    name: 'CyberMaxx',
    description: 'Nashville-based MSSP providing managed detection and response, vulnerability management, and security operations for the mid-market.',
    website: 'https://www.cybermaxx.com',
    founded_year: 2002,
    headquarters: 'Nashville, TN',
    city: 'Nashville',
    state: 'Tennessee',
    state_code: 'TN',
    employee_count: '50-200',
    industries_served: ['healthcare', 'finance', 'manufacturing', 'technology'],
    services: ['managed-security', 'vulnerability-management', 'incident-response', 'compliance-assessment'],
  },
];

// ============================================================
// CITIES (50 US metros)
// ============================================================

export const CITIES = [
  { slug: 'houston-tx', name: 'Houston', state: 'Texas', state_code: 'TX', population: 2304580 },
  { slug: 'dallas-tx', name: 'Dallas', state: 'Texas', state_code: 'TX', population: 1304379 },
  { slug: 'austin-tx', name: 'Austin', state: 'Texas', state_code: 'TX', population: 978908 },
  { slug: 'san-antonio-tx', name: 'San Antonio', state: 'Texas', state_code: 'TX', population: 1434625 },
  { slug: 'new-york-ny', name: 'New York', state: 'New York', state_code: 'NY', population: 8336817 },
  { slug: 'los-angeles-ca', name: 'Los Angeles', state: 'California', state_code: 'CA', population: 3979576 },
  { slug: 'chicago-il', name: 'Chicago', state: 'Illinois', state_code: 'IL', population: 2693976 },
  { slug: 'phoenix-az', name: 'Phoenix', state: 'Arizona', state_code: 'AZ', population: 1608139 },
  { slug: 'philadelphia-pa', name: 'Philadelphia', state: 'Pennsylvania', state_code: 'PA', population: 1603797 },
  { slug: 'san-diego-ca', name: 'San Diego', state: 'California', state_code: 'CA', population: 1386932 },
  { slug: 'denver-co', name: 'Denver', state: 'Colorado', state_code: 'CO', population: 715522 },
  { slug: 'seattle-wa', name: 'Seattle', state: 'Washington', state_code: 'WA', population: 737015 },
  { slug: 'atlanta-ga', name: 'Atlanta', state: 'Georgia', state_code: 'GA', population: 498715 },
  { slug: 'miami-fl', name: 'Miami', state: 'Florida', state_code: 'FL', population: 442241 },
  { slug: 'boston-ma', name: 'Boston', state: 'Massachusetts', state_code: 'MA', population: 675647 },
  { slug: 'minneapolis-mn', name: 'Minneapolis', state: 'Minnesota', state_code: 'MN', population: 429954 },
  { slug: 'charlotte-nc', name: 'Charlotte', state: 'North Carolina', state_code: 'NC', population: 874579 },
  { slug: 'nashville-tn', name: 'Nashville', state: 'Tennessee', state_code: 'TN', population: 689447 },
  { slug: 'portland-or', name: 'Portland', state: 'Oregon', state_code: 'OR', population: 652503 },
  { slug: 'las-vegas-nv', name: 'Las Vegas', state: 'Nevada', state_code: 'NV', population: 641903 },
  { slug: 'detroit-mi', name: 'Detroit', state: 'Michigan', state_code: 'MI', population: 639111 },
  { slug: 'memphis-tn', name: 'Memphis', state: 'Tennessee', state_code: 'TN', population: 633104 },
  { slug: 'baltimore-md', name: 'Baltimore', state: 'Maryland', state_code: 'MD', population: 585708 },
  { slug: 'milwaukee-wi', name: 'Milwaukee', state: 'Wisconsin', state_code: 'WI', population: 577222 },
  { slug: 'tampa-fl', name: 'Tampa', state: 'Florida', state_code: 'FL', population: 384959 },
  { slug: 'st-louis-mo', name: 'St. Louis', state: 'Missouri', state_code: 'MO', population: 301578 },
  { slug: 'orlando-fl', name: 'Orlando', state: 'Florida', state_code: 'FL', population: 307573 },
  { slug: 'sacramento-ca', name: 'Sacramento', state: 'California', state_code: 'CA', population: 524943 },
  { slug: 'kansas-city-mo', name: 'Kansas City', state: 'Missouri', state_code: 'MO', population: 508090 },
  { slug: 'indianapolis-in', name: 'Indianapolis', state: 'Indiana', state_code: 'IN', population: 887642 },
  { slug: 'san-francisco-ca', name: 'San Francisco', state: 'California', state_code: 'CA', population: 873965 },
  { slug: 'washington-dc', name: 'Washington', state: 'District of Columbia', state_code: 'DC', population: 689545 },
  { slug: 'columbus-oh', name: 'Columbus', state: 'Ohio', state_code: 'OH', population: 905748 },
  { slug: 'san-jose-ca', name: 'San Jose', state: 'California', state_code: 'CA', population: 1013240 },
  { slug: 'fort-worth-tx', name: 'Fort Worth', state: 'Texas', state_code: 'TX', population: 918915 },
  { slug: 'jacksonville-fl', name: 'Jacksonville', state: 'Florida', state_code: 'FL', population: 949611 },
  { slug: 'raleigh-nc', name: 'Raleigh', state: 'North Carolina', state_code: 'NC', population: 467665 },
  { slug: 'pittsburgh-pa', name: 'Pittsburgh', state: 'Pennsylvania', state_code: 'PA', population: 302971 },
  { slug: 'cincinnati-oh', name: 'Cincinnati', state: 'Ohio', state_code: 'OH', population: 309317 },
  { slug: 'salt-lake-city-ut', name: 'Salt Lake City', state: 'Utah', state_code: 'UT', population: 200133 },
  { slug: 'richmond-va', name: 'Richmond', state: 'Virginia', state_code: 'VA', population: 226610 },
  { slug: 'oklahoma-city-ok', name: 'Oklahoma City', state: 'Oklahoma', state_code: 'OK', population: 681054 },
  { slug: 'hartford-ct', name: 'Hartford', state: 'Connecticut', state_code: 'CT', population: 121054 },
  { slug: 'new-orleans-la', name: 'New Orleans', state: 'Louisiana', state_code: 'LA', population: 383997 },
  { slug: 'birmingham-al', name: 'Birmingham', state: 'Alabama', state_code: 'AL', population: 200733 },
  { slug: 'louisville-ky', name: 'Louisville', state: 'Kentucky', state_code: 'KY', population: 633045 },
  { slug: 'omaha-ne', name: 'Omaha', state: 'Nebraska', state_code: 'NE', population: 486051 },
  { slug: 'tucson-az', name: 'Tucson', state: 'Arizona', state_code: 'AZ', population: 542629 },
  { slug: 'el-paso-tx', name: 'El Paso', state: 'Texas', state_code: 'TX', population: 678815 },
  { slug: 'honolulu-hi', name: 'Honolulu', state: 'Hawaii', state_code: 'HI', population: 350964 },
];
